# docker-compose.dev.yml
services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "ultiscore"]
      interval: 5s
      timeout: 10s
      retries: 5
  web:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    # Set envrionment variables based on the .env file
    env_file:
      - .env
    # Set environment variables directly in the docker-compose file
    # environment:
    #   POSTGRES_ADDR: postgres
    #   POSTGRES_DATABASE: ultiscore
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app/next-app
    restart: always
    ports:
      - 3000:3000

volumes:
  pgdata: {}
