name: Migrate
on:
  push:
    branches: [main, master]
jobs:
  migrate:
    environment: production
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: create env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
      - name: Install dependencies
        run: npm ci
      - name: Run Migration
        run: npx prisma migrate deploy
